UI/Areas/Admin/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DTO;
using BLL;

namespace UI.Areas.Admin.Controllers
{
    public class AddressController : BaseController
    {
        AddressBLL bll = new AddressBLL();

        // GET: Admin/Address
        public ActionResult AddAddress()
        {
            AddressDTO dto = new AddressDTO();
            return View(dto);
        }
        [HttpPost]
        [ValidateInput(false)] //--> To prevent errors when saving the maps with the <iframe>
        public ActionResult AddAddress(AddressDTO model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ProcessState = General.Messages.EmptyArea;
            }
            else
            {
                if (bll.AddAddress(model))
                {
                    ViewBag.ProcessState = General.Messages.AddSuccess;
                    ModelState.Clear();
                    model = new AddressDTO();
                }
                else
                {
                    ViewBag.ProcessState = General.Messages.GeneralError;
                }
            }
            return View(model);
        }

        public ActionResult AddressList()
        {
            List<AddressDTO> dto = new List<AddressDTO>();
            dto = bll.GetAddresses();
            return View(dto);
        }

        public ActionResult UpdateAddress(int ID)
        {
            AddressDTO dto = new AddressDTO();
            dto = bll.GetAddressWithID(ID);
            return View(dto);
        }
        [HttpPost]
        [ValidateInput(false)] //--> To prevent errors when saving the maps with the <iframe>
        public ActionResult UpdateAddress(AddressDTO model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.ProcessState = General.Messages.EmptyArea;
            }
            else
            {
                if (bll.UpdateAddress(model))
                {
                    ViewBag.ProcessState = General.Messages.UpdateSuccess;
                    ModelState.Clear();
                    model = new AddressDTO();
                }
                else
                    ViewBag.ProcessState = General.Messages.GeneralError;
            }
            return View(model);
        }

        public JsonResult DeleteAddress(int ID)
        {
            bll.DeleteAddress(ID);
            return Json("");
        }
    }
}

UI/Areas/Admin/Views/Address/AddAddress.cshtml
@{
    ViewBag.Title = "AddAddress";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">
    <h1>Add Address</h1>
    <ol class=" breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Address</a></li>
        <li class="breadcrumb-item active"><a>Add Address</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/Address/AddressList'">Address List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("AddAddress", "Address", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/AddressForm")
                }
            </div>
        </div>
    </div>
</section>

UI/Areas/Admin/Views/Address/AddressList.cshtml
@{
    ViewBag.Title = "AddressList";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

@model List<DTO.AddressDTO>
<section class="content-header">
    <h1>Address List</h1>
    <ol class=" breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Address</a></li>
        <li class="breadcrumb-item active"><a>Address List</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/Address/AddAddress'">Add Address</button>
</div>

<div class="card">
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Address</th>
                    <th>Email</th>
                    <th>Phone1</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {

                    <tr id="a_@item.ID">
                        <td>@item.Address</td>
                        <td>
                            @item.Email
                        </td>
                        <td>
                            @item.Phone1
                        </td>
                        <td align="center" valign="middle">
                            <a href="/Admin/Address/UpdateAddress/@item.ID">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/arrow_circle_double.ico" />
                            </a>
                        </td>
                        <td align="center" valign="middle">
                            <a href="#">
                                <br />
                                <img src="~/Areas/Admin/Content/icons/remove.ico" onclick="AskQuestion('/Admin/Address/DeleteAddress/', @item.ID)"/>
                            </a>
                        </td>
                    </tr>

                }
            </tbody>
            <tfoot>
                <tr>
                    <th>Address</th>
                    <th>Email</th>
                    <th>Phone1</th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </tfoot>
        </table>
    </div>
    <!-- /.card-body -->
    @Html.Partial("~/Areas/Admin/Views/Shared/ModalMessage.cshtml")
</div>
<script src="~/Areas/Admin/Content/js/DeleteRecord.js"></script>
<!-- /.card -->

UI/Areas/Admin/Views/Address/UpdateAddress.cshtml
@{
    ViewBag.Title = "UpdateAddress";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<section class="content-header">
    <h1>Update Address</h1>
    <ol class=" breadcrumb float-sm-left">
        <li class="breadcrumb-item"><a>Admin</a></li>
        <li class="breadcrumb-item"><a>Address</a></li>
        <li class="breadcrumb-item active"><a>Update Address</a></li>
    </ol>
</section>
<br />
<div class="card-footer">
    <button type="submit" class="btn btn-primary" onclick="window.location.href='/Admin/Address/AddressList'">Address List</button>
</div>
<section class="content">
    <div class="row">
        <div class="col-md-9">
            @Html.Partial("~/Areas/Admin/Views/Shared/MessageForm.cshtml")
            <div class="box box-primary">
                @using (Html.BeginForm("UpdateAddress", "Address", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                {
                    @Html.Partial("Partial/AddressForm")
                }
            </div>
        </div>
    </div>
</section>